#!/bin/sh

case $0 in
*/dzcl)
	command=clean
	;;
*)
	exit 1;
	;;
esac

for i in `find . -type d \( -exec test -d '{}/.build' \; -print -prune -o -exec test -d '{}/.git' \; -prune \)`; do
	echo $i
	(cd $i; dzil $command)
done
