#!/bin/sh

if [ $# -lt 1 ]; then
    echo $0 '<file>'
    exit 1
fi

if [ `env PAGER= git log -n 1 -- $1 | wc -c` = 0 ]; then
    echo $1 is not under Git control
    exit 1
fi

if ! git diff --quiet HEAD -- $1; then
    echo $1 has differences not yet commit
    exit 1
fi

cur=`dirname $1`
tmp=`mktemp --tmpdir=$cur`
mv -f $1 $tmp
git hd $1
if diff $1 $tmp; then
    mv -f $tmp $1
else
    echo $1 updated
    rm $tmp
fi
