#!/bin/sh

case $0 in
*/glpl)
	command=pull
	filter="-exec grep -q \[branch {}/.git/config ;"
	;;
*/glst)
	command=status
	;;
*)
	exit 1;
	;;
esac
if [ -z "$1" ]; then
	dir=.
else
	dir=$1
fi

for i in `find $dir -type d -exec test -f '{}/.git/config' \; -prune $filter -print`; do
	if [ $command = status ]; then
		echo -n "$i :"
		temp=`mktemp`
		(cd $i; git $command > $temp)
		if grep -q 'Your branch is ahead' $temp; then
			echo -en " \033[1;31mAHEAD\033[0;0m"
		fi
		if grep -q 'Untracked' $temp; then
			echo -en ' \033[0;33mUNTRACK\033[0;0m'
		fi
		if grep -q 'nothing \(added \|\)to commit' $temp; then
			echo -n ' CLEAN'
		else
			echo -en ' \033[1;33mDIRTY\033[0;0m'
		fi
		rm $temp
		if (cd $i; git log -n 1 | grep -qE '[Uu]pdate.*after release|Released as'); then
			: 
		else
			echo -en " \033[0;32mWORK\033[0;0m"
                fi
		echo
	else
		echo $i
		(cd $i; git $command)
	fi
done
